FROM golang:1.18

WORKDIR /usr/src/app
COPY backend/go.mod backend/go.sum ./
RUN go mod download && go mod verify

COPY backend/ .

RUN go build -v -o /usr/local/bin/app ./cmd/main.go

ENTRYPOINT ["app"]
