#
# This is the CI/CD yml file for Beehive
#

docker-build:
  image: docker:20.10.18
  services:
    - docker:20.10.18-dind
  rules:
    - if: $CI_MERGE_REQUEST_DESTINATION_BRANCH_NAME != /master/
      when: never
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - |
      if [[ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "dev" ]]; then
        tag="staging"
      else if [[ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
      fi
    - docker build --pull -t $CI_REGISTRY_IMAGE${tag} --profile prod .
    - docker push $CI_REGISTRY_IMAGE
