name: BeeBuilt CI/CD Pipeline

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["dev", "main"]

env:
  GIT_USER_NAME: BeeBuilt Bot
  GIT_USER_EMAIL: beebuiltbot@login.no

jobs:
  fix-version:

    name: 🧩 Fix & Update Version
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.bump.outputs.new_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag for main and dev
        run: |
          main_version=$(git show origin/main:package.json 2>/dev/null | jq -r '.version' 2>/dev/null)
          dev_version=$(git show origin/dev:package.json 2>/dev/null | jq -r '.version' 2>/dev/null)
          echo "main_tag=$main_version" >> $GITHUB_ENV
          echo "dev_tag=$dev_version" >> $GITHUB_ENV

      - name: New version
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          main_tag="$main_tag"
          dev_tag="$dev_tag"
          new_version=""
          skip_commit=false

          git fetch origin main
          git fetch origin dev

          IFS='.' read -r main_major main_minor main_patch <<< "$main_tag"
          IFS='.' read -r dev_major dev_minor dev_patch <<< "$dev_tag"

          # Count changed files for patch/minor logic
          changed_files=$(git diff --name-only origin/main...HEAD | wc -l)
          echo "Changed files: $changed_files"

          if [ "$branch" = "main" ]; then
            # Check if main is behind dev
            if git merge-base --is-ancestor origin/main origin/dev; then
              echo "Main is behind Dev. Merging dev into main..."
              git config --global user.name "$GIT_USER_NAME"
              git config --global user.email "$GIT_USER_EMAIL"
              git merge --no-ff origin/dev -m "Merge dev into main to sync version $dev_tag"
              new_version="$dev_tag"
              skip_commit=true
            else
              # Main = Dev or normal bump logic
              if [ "$main_tag" = "$dev_tag" ]; then
                if [ "$changed_files" -lt 4 ]; then
                  patch=$((main_patch + 1))
                  minor=$main_minor
                else
                  patch=0
                  minor=$((main_minor + 1))
                fi
                new_version="$main_major.$minor.$patch"
                echo "Main = Dev. Bumping both Main and Dev to $new_version"
              elif [ "$main_major" -gt "$dev_major" ] || \
                  { [ "$main_major" -eq "$dev_major" ] && [ "$main_minor" -gt "$dev_minor" ]; } || \
                  { [ "$main_major" -eq "$dev_major" ] && [ "$main_minor" -eq "$dev_minor" ] && [ "$main_patch" -gt "$dev_patch" ]; }; then
                new_version="$main_tag"
                echo "Main > Dev. Updating Dev to match Main"
              fi
            fi
          elif [ "$branch" = "dev" ]; then
            # Always bump dev
            if [ "$changed_files" -lt 4 ]; then
              patch=$((dev_patch + 1))
              minor=$dev_minor
            else
              patch=0
              minor=$((dev_minor + 1))
            fi
            new_version="$dev_major.$minor.$patch"
            echo "Bumping Dev version to $new_version"
          else
            # Other branches: no automatic bump
            new_version="$main_tag"
            echo "Branch $branch: no automatic version bump"
          fi

          echo "new_version=$new_version" >> $GITHUB_ENV
          echo "skip_commit=$skip_commit" >> $GITHUB_ENV
          echo "Calculated new_version: $new_version"

      - name: Update package.json
        if: env.skip_commit != 'true'
        run: |
          find . -name "package.json" -not -path "*/node_modules/*" -not -path "*/vendor/*" -exec sh -c '
            file="$1"
            new_ver="${2#v}"
            sed -i "s/\"version\": \".*\"/\"version\": \"$new_ver\"/" "$file"
          ' _ {} "${{ env.new_version }}" \;

      - name: Update package-lock.json
        if: env.skip_commit != 'true'
        run: |
          find . -name "package-lock.json" -not -path "*/node_modules/*" -not -path "*/vendor/*" -exec sh -c '
            file="$1"
            new_ver="${2#v}"
            sed -i "s/\"version\": \".*\"/\"version\": \"$new_ver\"/" "$file"
          ' _ {} "${{ env.new_version }}" \;

      - name: Commit changes
        if: env.skip_commit != 'true'
        run: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          git pull
          git add $(find . -name "package.json" -o -name "package-lock.json" | grep -v node_modules | grep -v vendor)
          git commit -m "v${{ env.new_version }}" || echo "No changes to commit"
          git push origin $GITHUB_REF_NAME

      - name: Update package.json
        run: |
          find . -name "package.json" -not -path "*/node_modules/*" -not -path "*/vendor/*" -exec sh -c '
            file="$1"
            new_ver="${2#v}"
            if ! sed -n "3p" "$file" | grep -q "\"version\":"; then
              echo "Version not at line 3 in $file"
              exit 1
            fi
            sed -i "3s/\"version\": \"[^\"]*\"/\"version\": \"$new_ver\"/" "$file"
          ' _ {} "${new_version}" \;

      - name: Update lock file
        run: |
          find . -name "package-lock.json" -not -path "*/node_modules/*" -not -path "*/vendor/*" -exec sh -c '
            file="$1"
            new_ver="${2#v}"
            if ! sed -n "3p" "$file" | grep -q "\"version\":"; then
              echo "Version not at line 3 in $file"
              exit 1
            fi
            if ! sed -n "9p" "$file" | grep -q "\"version\":"; then
              echo "Version not at line 9 in $file"
              exit 1
            fi
            sed -i "3s/\"version\": \"[^\"]*\"/\"version\": \"$new_ver\"/" "$file"
            sed -i "9s/\"version\": \"[^\"]*\"/\"version\": \"$new_ver\"/" "$file"
          ' _ {} "${new_version}" \;

      - name: Commit changes
        if: env.skip_commit != 'true'
        run: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          git add $(find . -name "package.json" -o -name "package-lock.json" | grep -v node_modules | grep -v vendor)
          git commit -m "v${{ env.new_version }}" || echo "No changes to commit"
          git push origin $GITHUB_REF_NAME

      - name: Create Git Tag
        run: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"
          branch=$(git rev-parse --abbrev-ref HEAD)
          tag="${{ env.new_version }}"
          if [ "$branch" = "dev" ]; then
            tag="${{ env.new_version }}-dev"
          fi
          git tag "$tag"
          git push origin "$tag"

      - name: Create dev tag if not exists
        if: github.ref == 'refs/heads/main'
        run: |
          dev_tag="${{ env.new_version }}-dev"
          if ! git tag -l | grep -q "^${dev_tag}$"; then
            git tag $dev_tag
            git push origin $dev_tag
          fi

  rebase:
    name: 🔄 Rebase from main to dev
    runs-on: ubuntu-latest
    needs: fix-version
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout dev
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.name "$GIT_USER_NAME"
          git config --global user.email "$GIT_USER_EMAIL"

      - name: Rebase from main to dev
        run: |
          git rebase origin/main

      - name: Push dev
        run: git push origin dev

  build:
    name: 🐳 Build Containers
    runs-on: ubuntu-latest
    needs: fix-version

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 1Password Secrets Action
        uses: 1Password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        
      - name: Ensure curl exists
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: List 1Password items in repo vault
        run: |
          # Use repo name as vault/item prefix
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          echo "Looking for 1Password items in vault: $REPO_NAME"

      - name: Create .env file
        run: |
          echo "Generating .env file for Docker Compose"
          cat <<EOF > .env
          DOCKER_USER=${DOCKER_USER}
          DOCKER_PASS=${DOCKER_PASS}
          DISCORD_WEBHOOK=${DISCORD_WEBHOOK}
          EOF
          echo ".env file created:"
          cat .env

      - name: Login to Docker
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login "${{ secrets.DOCKER_REGISTRY }}" -u "${{ secrets.DOCKER_USER }}" --password-stdin
        
      - name: Build with Docker Compose
        run: docker compose up -d --build

      - name: Check exposed ports
        run: |
          ports=$(docker compose ps --format json \
            | jq -sr '.[] | .Publishers? // [] | .[] | .PublishedPort' \
            | sort -u)

          for port in $ports; do
            echo "🕓 Waiting for port $port to respond..."

            # Try up to 10 times with 5 seconds between
            for i in {1..10}; do
              code=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:$port || echo "000")
              if [ "$code" = "200" ]; then
                echo "✅ Port $port is ready (HTTP $code)"
                break
              else
                echo "⏳ Attempt $i: got code $code, retrying in 5s..."
                sleep 5
              fi
            done

            if [ "$code" != "200" ]; then
              echo "❌ Port $port failed with code $code after retries"
              curl -H "Content-Type: application/json" \
                -X POST \
                -d "{\"embeds\":[{\"title\":\"Validation Failed\",\"description\":\"Port $port returned code $code after retries\"}]}" \
                "$DISCORD_WEBHOOK"
              exit 1
            fi
          done

      - name: Install pup
        run: |
          curl -LO https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
          unzip pup_v0.4.0_linux_amd64.zip
          chmod +x pup
          sudo mv pup /usr/local/bin/
          pup --help

      - name: Validate UI routes & elements
        run: |
          if nc -z localhost 3000; then
            echo "Port 3000 is open, proceeding with validation..."
            SPEC=$(cat .test.json)
            for PATH in $(echo "$SPEC" | jq -r 'keys[]'); do
              echo "Checking $PATH ..."
              HTML=$(curl -qO- "http://localhost:3000$PATH")
              for ELEM in $(echo "$SPEC" | jq -r --arg path "$PATH" '.[$path][]'); do
                echo "  Checking element $ELEM ..."
                FOUND=$(echo "$HTML" | pup "[data-testid=\"$ELEM\"]" | wc -l)
                if [ "$FOUND" -eq 0 ]; then
                  echo "❌ Element $ELEM not found at $PATH"
                  exit 1
                fi
              done
            done
          else
            echo "Port 3000 not open — skipping route validation."
          fi

      - name: Collect logs
        run: |
          mkdir -p logs
          docker ps --format '{{.Names}}' | while read name; do
            echo "Capturing $name"
            docker logs $name > "logs/${name}.log" || true
          done

      - name: Tag & Push
        run: |
          IMAGE="${{ secrets.DOCKER_REGISTRY }}/tekkom/dev/${{ github.ref_name }}"
          VERSION=${{ needs.fix-version.outputs.new_tag }}

          echo "Image: $IMAGE"
          echo "Version: $VERSION"

          # Build all services
          docker compose build

          # Get all service names from docker-compose.yml
          SERVICES=$(docker compose config --services)

          if [ -z "$SERVICES" ]; then
            echo "❌ No services found in docker-compose.yml"
            exit 1
          fi

          # Loop over services and tag/push each
          for SERVICE in $SERVICES; do
            echo "Processing service: $SERVICE"
            IMAGE_ID=$(docker compose images -q $SERVICE)
            if [ -z "$IMAGE_ID" ]; then
              echo "❌ No image found for service $SERVICE"
              exit 1
            fi

            docker tag "$IMAGE_ID" "$IMAGE-$SERVICE:$VERSION"
            docker push "$IMAGE-$SERVICE:$VERSION"
          done

  update:
    name: 🔄 Update Kubernetes Repo
    runs-on: ubuntu-latest
    needs: [build, fix-version]
    steps:
      - name: Determine repo path
        id: set_repo
        run: |
          if [ "${GITHUB_REF##*/}" = "here" ]; then
            echo "repo_name=infra-prod-cluster" >> $GITHUB_ENV
          else
            echo "repo_name=test-cluster" >> $GITHUB_ENV
          fi

      - name: Checkout kube repo
        uses: actions/checkout@v4
        with:
          repository: Login-Linjeforening-for-IT/${{ env.repo_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          path: kuberepo

      - name: Update image version
        run: |
          cd kuberepo
          yq e -i '.spec.template.spec.containers[0].image = "${{ secrets.DOCKER_REGISTRY }}/${GITHUB_REF##*/}:${{ needs.fix-version.outputs.new_tag }}"' deployment.yaml
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update BeeBuilt image to ${{ needs.fix-version.outputs.new_tag }}"
          git push
